### PR TITLE
Added image as requested in issue #84

### PR DESCRIPTION
**Pull request by mettelilienthal**
## Issue ticket number and link

see also https://github.com/asam-ev/OpenMATERIAL/pull/87

@LudwigFriedmann please review.

### CODE REVIEW

**Comment by ClemensLinnhoff** [comment]
This image is not linked anywhere. Also, the axis don't match ISO 8855, as we have x,y,z and not u,v,z.

**Comment by mettelilienthal** [comment]
It will be linked in the Coordinate systems subchapter. There, the axis are listed as x,y,z which is why I assumed the image should match the text.
I got the information on the axis from the documentation:
image

and the Miroboard accordingly (https://miro.com/app/board/uXjVNrdmIpM=/?moveToWidget=3458764583130364723&cot=10)

**Comment by mettelilienthal** [comment]
@ACMackenthun has experience with coordinate systems and this kind of documentation. She will be checking the documentation content to ensure all content is correct from our side. :)

**Comment by ClemensLinnhoff** [comment]
> It will be linked in the Coordinate systems subchapter. There, the axis are listed as x,y,z which is why I assumed the image should match the text.

Exactly. But it does not. In the image it says u and v on the x- and y- axes.

**Comment by ACMackenthun** [comment]
I closed the pull request, because we will add all images and the related descriptions in PR https://github.com/asam-ev/OpenMATERIAL/pull/87/files

**Pull request closed without merging**
