### PR TITLE
Add more detailed definition for BRDF

### PR DESCRIPTION
**Pull request by DavidJRitter904**
## Describe your changes

Added a more detailed definition of the BRDF in the description field based on the references stated in #236 and [Hapke](https://books.google.at/books?id=3FNzaFuoXY0C&lpg=PP1&hl=de&pg=PP1#v=onepage&q&f=false).

## Issue ticket number and link

#254 

## Mention a member

@KimuraDIVP @ClemensLinnhoff @lyndyRott @Norihito-Hiruma 
Ready for review

## Checklist before requesting a review

- [ ] I have performed a self-review of my code/documentation.
- [ ] My changes generate no new warnings during the documentation generation.

### CODE REVIEW

**Review by lyndyRott — COMMENTED** [review]
Well done. It makes sense to me to use this definition which refers to an angle pair (collimated ray "input") as opposed to the albedo from remote-sensing, where the incoming direction might not be known or arbitrary and thus the entire half-space is used.

**Comment by TimoHinsemann** [comment]
Sounds very good, thank you very much! One thing I would like to add to the description - As far as I know, the part "...Could vary from 0 to infinity. It is symmetric in the incoming and outgoing direction, known as the Helmholtz reciprocity principle." is not part of the BRDF-Definition, but means that a BRDF is "physically plausible" (See Montes and Urena: https://digibug.ugr.es/bitstream/handle/10481/19751/rmontes_LSI-2012-001TR.pdf ; Page 3). So a BRDF is physically plausible, when it is non-negative (1), obeys symmetry (Helmholtz Reciprocity) (2) and no more radiant energy is reflected than the incident energy (3). 

Thats why I would prefer to add these 3 mentioned properties as "requirements" for a "physically plausible" BRDF, and not the BRDF-Definition. Also we could have a problem with the "symmetry" when it comes to measured BRDFs, which would be another reason to exclude the properties from the BRDF-Definition.

**Comment by Norihito-Hiruma** [comment]
Thank you so much.
I think it's a very polite and good additional explanation.

**Comment by lyndyRott** [comment]
> Sounds very good, thank you very much! One thing I would like to add to the description - As far as I know, the part "...Could vary from 0 to infinity. It is symmetric in the incoming and outgoing direction, known as the Helmholtz reciprocity principle." is not part of the BRDF-Definition, but means that a BRDF is "physically plausible" (See Montes and Urena: https://digibug.ugr.es/bitstream/handle/10481/19751/rmontes_LSI-2012-001TR.pdf ; Page 3). So a BRDF is physically plausible, when it is non-negative (1), obeys symmetry (Helmholtz Reciprocity) (2) and no more radiant energy is reflected than the incident energy (3).
> 
> Thats why I would prefer to add these 3 mentioned properties as "requirements" for a "physically plausible" BRDF, and not the BRDF-Definition. Also we could have a problem with the "symmetry" when it comes to measured BRDFs, which would be another reason to exclude the properties from the BRDF-Definition.

To provide the 3 properties makes sense, as it is done in various literature sources. Property (3) could also be shortened to the term "energy conservation", under which it is typically known.

**Comment by ClemensLinnhoff** [comment]
Okay, @DavidJRitter904 would you add this addition from Timo? Then I think we are ready to merge.

**Comment by DavidJRitter904** [comment]
Thank you for your feedback!
I have added the three properties for a physical plausible BRDF to the description. 
The part with the variation of of the units between 0 and infinity is added as there can be high radiance in exit direction due to arbitrary small irradiance. 

I think now we have a very elaborate definition.

**Review by ClemensLinnhoff — APPROVED** [review]

**Pull request merged**
