### PR TITLE
Links and arrangement in object structures

### PR DESCRIPTION
**Pull request by FKlopfer**
## Describe your changes

- Add links to the table of content that bring the user directly to the respective section. This needs to be done for all classes (vehicle, human and road network).
- Sort the individual elements within one hierarchy level in alphabetical order. This entails changing the order in the structure overview (table of content) and also the order of the corresponding sub-sections.
- And let's rename the section "Table of content" to "Structure overview" because it actually represents more than just a toc because it also shows the hierarchy levels.

## Issue ticket number and link

[Add a reference to a related issue.](https://github.com/asam-ev/OpenMATERIAL/issues/147)

### CODE REVIEW

**Comment by FKlopfer** [comment]
@ClemensLinnhoff , the structure has been updated:

- The table of content now contains links to the respective sections, see example: 
image
- The sections are ordered alphabetically (in the table of content and in the chapter)
- Section is called "Structure overview"

**Comment by ClemensLinnhoff** [comment]
Looks good. Is this ready to be merged? Because the PR is still marked as Draft.

**Comment by ClemensLinnhoff** [comment]
And please resolve the merge conflicts.

**Comment by FKlopfer** [comment]
Resolve merge conflict and mark PR as "ready for review".

**Review by ClemensLinnhoff — APPROVED** [review]

**Pull request merged**
