### PR TITLE
Rework BRDF definition and add reflectance lookup table

### LINKED ISSUE #167: Revisit amplitudeUnit in BRDF definition
#### Describe the problem
Currently we have the field "amplitudeUnit" that can either be "1/sr" or "linear".
1/sr is the standard unit for BRDFs.
According to the proposal linear would be mainly used for radar. But we have not defined yet, what linear really means. 

#### Describe your research
A BRDF describes the ratio of reflected radiance along a certain angle to the irradiance incident on the surface from a certain direction.
So the BRDF values are always per angle.
From my research the unit of a BRDF (regardless of wavelength) is therefore always 1/sr.

#### Ask your question
Do we really need the amplitudeUnit parameter? And if yes, how exactly is the linear scaling defined?

@Norihito-Hiruma, @KimuraDIVP could you comment on this?

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
## Describe your changes

- Remove polarization, phase and the amplitude unit from BRDF definition
- Add reflectance table as proposed in #200 

## Issue ticket number and link

Fixes #167

## Checklist before requesting a review

- [x] I have performed a self-review of my code/documentation.
- [x] My changes generate no new warnings during the documentation generation.

### CODE REVIEW

**Comment by ClemensLinnhoff** [comment]
@Norihito-Hiruma I incorporated your changes from #200 here. Please review this branch. Does this fit to your proposal?

**Comment by ClemensLinnhoff** [comment]
> @Norihito-Hiruma I incorporated your changes from #200 here. Please review this branch. Does this fit to your proposal?

If this fits your expectations, @KimuraDIVP please approve this PR so we can merge.

**Comment by Norihito-Hiruma** [comment]
Clemens-san, I have confirmed the contents.
So you changed the wavelength to the first item in the table.
Got it. There is no problem with the content.

**Comment by ClemensLinnhoff** [comment]
After #233 is merged, adjust the following:
- Remove typicalSensor to typicalSensorTechnology
- Move typicalSensorTechnology to metadata
- Change wavelengthRange to wavelengths and instead of putting min and max value in it list all contained wavelengths

**Comment by ClemensLinnhoff** [comment]
This is ready of review @KimuraDIVP, @AsamDiegoSanchez

**Review by AsamDiegoSanchez — APPROVED** [review]
General review i.O.
Signed-Off by: Diego Sánchez <diego.sanchez@asam.net>

**Pull request merged**
