### PR TITLE
add vehicle class dependent metadata

### PR DESCRIPTION
**Pull request by MustafaTrian**
## Describe your changes

Add vehicle class dependent metadata to asset schema file following https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/Vehicle.html

the original Axle object defined by https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/Axles.html is a little bit misleading; the text description and properties describe additionalAxles
as list of (additional) axle that is an elemnt in the Axles list.
However, the XSD 1.0 Representation states that additional axles are simply axles and are direct sub elements in the Axles array forcing all of them to have the unified name "additionalAxle":
 <xsd:element name="AdditionalAxle" type="[Axle](https://releases.asam.net/OpenSCENARIO/1.0.0/Model-Documentation/content/Axle.html)" minOccurs="0" maxOccurs="unbounded"/>
 I followed the XSD Representation.

Some tests were made on the schema against input json example on https://www.lddgo.net/en/string/json-schema

## Issue ticket number and link

[#71](https://github.com/asam-ev/OpenMATERIAL/issues/71)

## Mention a member

@ClemensLinnhoff 

## Checklist before requesting a review

- [x] I have performed a self-review of my code/documentation.
- [] My changes generate no new warnings during the documentation generation.

### CODE REVIEW

**Comment by ClemensLinnhoff** [comment]
Thank you @MustafaTrian for this!

I did some minor changes to the schema, e.g. I had to change the axles from an array to an object, because it has to have front and rear axle and only the additional axles is an array.

I also added some data to the vehicle example xoma file to test out the schema. It works quite well I think.

I am just not entirely sure if we really need the if-then condition. Because the vehicleClassData field is optional anyways. So I think we can just remove the if-then. This would make it much easier to parse the schema into the asciidoc documentation.
I will try this out in my next commit. We can revert it, if we decide we do need the if-then.

**Comment by ClemensLinnhoff** [comment]
Using the definitions for the axles is a very good idea. I just need some time to adjust the python script generating the documentation, because it is currently not capable of handling definitions.

**Comment by ClemensLinnhoff** [comment]
> Using the definitions for the axles is a very good idea. I just need some time to adjust the python script generating the documentation, because it is currently not capable of handling definitions.

This was actually a bit easier than I thought and I directly added it

**Comment by ClemensLinnhoff** [comment]
In my opinion this is ready to be merged.
What do you think @LudwigFriedmann @ipg-sig @MatthiasThDs @DavidJRitter904 @KimuraDIVP ?

**Review by ClemensLinnhoff — APPROVED** [review]

**Review by LudwigFriedmann — APPROVED** [review]
Looks good to me!

**Pull request merged**
