### PR TITLE
Add more description to the file format chapter

### LINKED ISSUE #61: Add supported file formats
**Is your feature request related to a problem? Please describe.**
The OpenMATERIAL Geometry is not defining own 3D model formats. Specific existing formats will be officially supported.

**Describe the solution you'd like**
Add a description to the documentation that the following formats are supported:

- glTF
- FBX
- USD

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
## Describe your changes

Add a bit more description to the supported file formats. The list of file formats was already on the main branch.

## Issue ticket number and link

Fixes #61 

## Checklist before requesting a review

- [x] I have performed a self-review of my code/documentation.
- [x] My changes generate no new warnings during the documentation generation.

### CODE REVIEW

**Comment by ClemensLinnhoff** [comment]
@FKlopfer it is only a very small PR, but please check for spelling and phrasing.

**Comment by FKlopfer** [comment]
Language check done

**Review by FKlopfer — APPROVED** [review]

**Comment by ClemensLinnhoff** [comment]
@LudwigFriedmann @KimuraDIVP @AsamDiegoSanchez could you review this minor MR? With your approvals we can merge this.

**Review by AsamDiegoSanchez — APPROVED** [review]
Agree on merging. No remarks from my side

Signed-off-by: Diego Sánchez <diego.sanchez@asam.net>

**Comment by KimuraDIVP** [comment]
Yes I agree to merge.

**Review by KimuraDIVP — APPROVED** [review]
Yes, I agree to merge.

**Pull request merged**
