### PR TITLE
Road structure

### LINKED ISSUE #7: Evaluate OpenDRIVE
Evaluate ASAM OpenDRIVE (https://www.asam.net/standards/detail/opendrive/) as basis for road network model structure

### PR DESCRIPTION
**Pull request by mettelilienthal**
## Describe your changes

added initial files for road network together with the sticky note comments from the Miroboard

## Mention a member
@FKlopfer please review

Fixes #7

### CODE REVIEW

**Comment by FKlopfer** [comment]
@LudwigFriedmann , we created the initial structure of the road network chapter based on the Miro board, please review.

**Comment by mettelilienthal** [comment]
Deleted railway-related topics according to decision in meeting on 25/07/2024

**Review by LudwigFriedmann — DISMISSED** [review]
1. Asciidoc creation fails with "file not found" errors
Railroad_Railroad_idx.adoc
Main_Track_Main_track_idx.adoc
Side_Track_Side_track_idx.adoc
Switch_Switch_idx_T.adoc
Station_Station_idx.adoc
Platform_Platform_idx.adoc
Segment_Segment_idx.adoc

Since it was decided to postpone railway integration, anyhow, please remove these references.

2. Please add a top level entry and a corresponding file "Notes", containing a bullet point list of the discussion results (post-its) from the miro board.

3. In order to integrate the model structure in an overarching document, I'd extend the table of content by the chapters "Introduction", "General" and "Model Creation":

|- Introduction
|- General
|- Model Creation
|- Model Structure
| |- ... current toc content ...
|- Notes

4. Please check for consistenty in naming, especially concerning the iterators (should be lower case, e.g. "road_idx" instead of "Road_idx"

**Comment by FKlopfer** [comment]
Regarding the requested changes:
1. Removed references to before deleted files about railways.
2. Add "notes" file with the notes from the Miro board
3. Add general topics and link them
4. Unify naming. It now looks like that for every node (lane marking as example): "Lane Marking (lane_marking_idx)"

**Comment by ClemensLinnhoff** [comment]
@LudwigFriedmann could you re-review the changes made by @FKlopfer based on your remarks?
I would suggest we make this structural MR ready to be merged and fill in the descriptions and definitions in a new MR.

**Comment by LudwigFriedmann** [comment]
The table of content seems to be removed from this chapter. As it serves as visualization of the hierarchical structure, can we have it back?

**Comment by ClemensLinnhoff** [comment]
> The table of content seems to be removed from this chapter. As it serves as visualization of the hierarchical structure, can we have it back?

@nakohdo please process the same way as described here: https://github.com/asam-ev/OpenMATERIAL/pull/35#issuecomment-2285819796

**Comment by ClemensLinnhoff** [comment]
I think this will fix #7, so I added it to the PR description.

**Comment by ClemensLinnhoff** [comment]
I fixed adjusted the file structure analog to the vehicle structure. @mettelilienthal please fix the hierarchy visualization as described in #77.

**Review by LudwigFriedmann — APPROVED** [review]
Fixed

**Pull request merged**
