### PR TITLE
Review Metadata section in asset schema #136

### PR DESCRIPTION
**Pull request by MustafaTrian**
## Describe your changes
- Added some more detailed description on every element of the metadata in the asset schema
- few units and data types were clearly written
- a url to the asset file chapter (7.2.4) was added. 

## Issue ticket number and link

Add a reference to a related issue.

## Mention a member

Add @mentions of the person or team responsible for reviewing the proposed changes.

## Checklist before requesting a review

- [x] I have performed a self-review of my code/documentation.
- [ ] My changes generate no new warnings during the documentation generation.

### CODE REVIEW

**Comment by LudwigFriedmann** [comment]
Ready to review after illustrations are added

**Comment by MustafaTrian** [comment]
so i edited descriptions of some elements in the asset_schema.json
As i couldn't figure out how the json2asciidoc.py gonna deal with the newlines, tabs or escape characters, i will post the "illustrations" here , it would be nice if it could be added to the json alongside the images. Could you take care of this please as discussed today? @ClemensLinnhoff :
[illustrations_AssetFile_Metadata.txt](https://github.com/user-attachments/files/17846893/illustrations_AssetFile_Metadata.txt)

**Comment by ClemensLinnhoff** [comment]
> so i edited descriptions of some elements in the asset_schema.json As i couldn't figure out how the json2asciidoc.py gonna deal with the newlines, tabs or escape characters, i will post the "illustrations" here , it would be nice if it could be added to the json alongside the images. Could you take care of this please as discussed today? @ClemensLinnhoff : [illustrations_AssetFile_Metadata.txt](https://github.com/user-attachments/files/17846893/illustrations_AssetFile_Metadata.txt)

Thanks. Unfortunately, json schema files do not allow line breaks. So the entire description has to be in one line. That's why bullet points also don't work unfortunately. Also, the text looks a bit AI generated. Some of it is slightly generic in my opinion.

**Comment by MustafaTrian** [comment]
ready for review

**Comment by ClemensLinnhoff** [comment]
I made some minor editorial changes.
One bigger thing is, that I removed the example for the PBR workflow, because the workflow metadata is only about the internal material definition in the 3D model file and not the mapped OpenMATERIAL properties.

But now this is ready to be merged in my opinion.

**Review by ClemensLinnhoff — APPROVED** [review]

**Pull request merged**
