### PR TITLE
General structure in material subgroup

### PR DESCRIPTION
**Pull request by FKlopfer**
## Describe your changes

Add initial content for general structure topics in material subgroup (three empty topics about metadata, fileformat, material parameters).

@AsamDiegoSanchez ,  I did not find Matty Daley or Danny Schambach in the GitHub repo so I cannot assign the PR to them so they can start writing content. Can you add them?

### CODE REVIEW

**Review by ClemensLinnhoff — APPROVED** [review]

**Comment by ClemensLinnhoff** [comment]
Why do we need the "general-structure" folder? In my understanding all content will go into these files.

**Comment by ClemensLinnhoff** [comment]
> Why do we need the "general-structure" folder? In my understanding all content will go into these files.

To elaborate: I would like to add an introduction chapter. After that we should only have the 3 given chapters as individual files, so:

- Introduction
- File Format
- Meta Data
- Material Parameters

(I changed the order a little bit)

**Review by AsamDiegoSanchez — APPROVED** [review]
No remarks from my side

Signed-off-by: Diego Sánchez <diego.sanchez@asam.net>

**Comment by ClemensLinnhoff** [comment]
CCB decision 02.08.24: Merge after chapters are set up.

**Comment by FKlopfer** [comment]
Implement changes as discussed in CCB.

**Comment by ClemensLinnhoff** [comment]
> Implement changes as discussed in CCB.

The chapters still need to be added to the main structure of the documentation. Otherwise they will not be visible in the generated html documentation.

**Comment by FKlopfer** [comment]
To avoid merge conflicts in the index file and antora-nav file, I added the references to the chapter in the other open PR (https://github.com/asam-ev/OpenMATERIAL/pull/36) . If this PR here is merged, and the other one after that, changes of both PRs should show up in the html documentation.

**Comment by ClemensLinnhoff** [comment]
> To avoid merge conflicts in the index file and antora-nav file, I added the references to the chapter in the other open PR (#36) . If this PR here is merged, and the other one after that, changes of both PRs should show up in the html documentation.

I merged the other MR.

**Comment by ClemensLinnhoff** [comment]
> > To avoid merge conflicts in the index file and antora-nav file, I added the references to the chapter in the other open PR (#36) . If this PR here is merged, and the other one after that, changes of both PRs should show up in the html documentation.
> 
> I merged the other MR.

But check out #54 first. There seem to be some bugs in the geometry structure, that might also affect the material structure.

**Comment by FKlopfer** [comment]
Updated structure and change heading.

**Pull request merged**
