### PR TITLE
Add asset meta data

### LINKED ISSUE #62: Add asset meta data
**Is your feature request related to a problem? Please describe.**
The geometry group has discussed as set of meta data for the asset file.

**Describe the solution you'd like**
Add the following meta data to the asset schema and the asset example:

- Name (Free field)
- Unique ID (UUID)
- Asset Version (Major.Minor.Patch .e.g 1.2.3)
- OpenMATERIAL Version (Major.Minor.Patch .e.g 1.2.3)
- Author (Free field)
- 3D Model Creation Tool (Free field)
- Creation Date (Date format)
- Modeling Method (e.g. 3D scan, modelled by image, public ressource,...) (Free text)
- Description Field (Free text)
- Copyright Information (Notice/Protection)
- License (CC0, GPL, url to license, filename of license file) (Free text)
- Asset type (scene, object)
- Object class (vehicle, human, road network, other) (List)
- Functionality level (e.g. Defined for object class (Only one node, most of the nodes, all of the nodes))
- Animated (Boolean)
- Material workflow (Metallic, Specular) (Either or)
- Bounding Box (+- for x,y,z)
- Complexity information (Mesh/Texture resolution or class (Real-Time, Non-Real-Time)...)
- Triangle count (e.g. one quad counts as two triangles)
- Texture resolution (e.g. 2K, 4K) (List)
- Number of objects (only for asset type scene) (int)
- Normal map format (DirectX or OpenGL)
- Validation description (Free text)
- Class dependent meta data
  - Vehicles:
    - Center of front axis w.r.t origin (x,y center, z at bottom)
    - Center of rear axis w.r.t origin (x,y center, z at bottom)

**Additional context**
This is not a comprehensive list, but it's a good starting point.

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
## Describe your changes

Add the following meta data:

- [x] Name (Free field)
- [x] Description (Free text)
- [x] Unique ID (UUID)
- [x] Asset Version (Major.Minor.Patch .e.g 1.2.3)
- [x] OpenMATERIAL Version (Major.Minor.Patch .e.g 1.2.3)
- [x] Copyright Information (Notice/Protection)
- [x] License (CC0, GPL, url to license, filename of license file) (Free text)
- [x] Author (Free field)
- [x] 3D Model Creation Tool (Free field)
- [x] Creation Date (Date format)
- [x] Modeling Method (e.g. 3D scan, modelled by image, public ressource,...) (Free text)
- [x] Validation description (Free text)
- [x] Asset type (scene, object)
- [x] Number of objects (only for asset type scene) (int)
- [x] Object class (vehicle, human, road network, other) (List)
- [x] Animated (Boolean)
- [x] Material workflow (Metallic, Specular) (Either or)
- [x] Triangle count (e.g. one quad counts as two triangles)
- [x] Texture resolution (e.g. 2K, 4K) (List)
- [x] Normal map format (DirectX or OpenGL)
- [x] Bounding Box (+- for x,y,z)
- [x] Class dependent metadata
  - [x] Vehicles:
    - [x] Center of front axis w.r.t origin (x,y center, z at bottom)
    - [x] Center of rear axis w.r.t origin (x,y center, z at bottom)

## Issue ticket number and link

Fixes #62

## Checklist before requesting a review

- [x] I have performed a self-review of my code/documentation.
- [x] My changes generate no new warnings during the documentation generation.

### CODE REVIEW

**Comment by ClemensLinnhoff** [comment]
I added all metadata discussed in the project meeting on 08.08.2024.

**Comment by ClemensLinnhoff** [comment]
@nakohdo The metadata in the asset schema from this pull request should replace [this asciidoc file](https://github.com/asam-ev/OpenMATERIAL/blob/main/content/geometry/Metadata.adoc). So this is a good place to test the automatic parsing of json data into asciidoc described in #52.

**Comment by ClemensLinnhoff** [comment]
Feel free to review and comment: @MatthiasThDs, @ipg-sig, @LudwigFriedmann, @KimuraDIVP

**Comment by ipg-sig** [comment]
Proposal

Mandatory: 
- Name 
- Unique ID 
- Asset Version
- OpenMATERIAL Version 
- Copyright Information 
- License 
- Author 
- Asset type
- Number of objects
- Animated 
- Material workflow 
- Triangle count 
- Texture resolution 
- Bounding Box
- Level of Detail (Boolean)

Add Class dependent metadata
Vehicles:
- Seat positions and corresponding eye levels (keep it the same like the vehicle axles, counting from right to left (in positive y-direction))
- Min an Max rotation level (for dynamic parts which can be transofrmed by the simulation)
Pedestrians, Animals (animated assets):
- List of included animations (idle, walk, run, etc.)
- Recommended velocity for each animation

**Comment by ClemensLinnhoff** [comment]
As discussed in the meeting today, I removed the object class dependent metadata from this PR and created two new issues for that: #71, #72.
I also specified the required fields as discussed in the meeting.

Please review @ipg-sig, @MatthiasThDs, @KimuraDIVP and @LudwigFriedmann so we can merge.

**Review by KimuraDIVP — APPROVED** [review]
seems alright.

**Review by LudwigFriedmann — APPROVED** [review]
Counterchecked with miro board information. Looks good!

**Pull request merged**
