### PR TITLE
Material mapping and assignment

### LINKED ISSUE #46: Methods of material assignment
**Is your feature request related to a problem? Please describe.**
Material files need to be linked to the geometry. There are different possibilities to do that. It needs to be decided if the standard should allow multiple mapping solutions and if yes, which ones.

**Describe the solution you'd like**
In the material group the following methods have been discussed:

- Assigning materials via vertex IDs
- Assigning materials via individual meshes
- Assigning materials via a texture map

### LINKED ISSUE #51: Enable material mapping through an external file
The first draft https://github.com/asam-ev/OpenMATERIAL/pull/29/files puts the material mapping directly into the asset file.
It should also be possible to refer to an external file for material mapping.

### Use cases:
- reuse of existing material mappings
- easier reassignment
- (generation from a 3D graphics software material library?)

### LINKED ISSUE #109: Material assignment in 3D models
**Is your feature request related to a problem? Please describe.**
There needs to be a way to assign a material ID to the geometry which can then be looked up in the OpenMATERIAL mapping table.

**Describe the solution you'd like**
Specify the name of an OpenMATERIAL assignment slot/channel, e.g. openMaterialAssignment

Assignment with a texture:

```json
"openMaterialAssignment": {
    "openMaterialAssignmentTexture": {
        "index": 1
    }
```

Assignment per mesh:

```json
"openMaterialAssignment": {
    "openMaterialAssignmentValue": [
        5,
        2,
        3,
        7
    ]
}
```

**Describe alternatives you've considered**

Specify a suffix for the texture files and look for the same base name as the albedo texture but with a different suffix. But this would only work for textures.

**Additional context**

Do conventional exporters, e.g. in Blender, support custom channels?
Are custom channels like this supported in all the formats (glTF, FBX an USD)?

### PR DESCRIPTION
**Pull request by ClemensLinnhoff**
## Describe your changes

- [x] Put material mapping in separate file.
- [x] Add texture assignment to asset file.
- [x] Restructure documentation to contain the different files.

Check out the implemented documentation on my fork:
https://clemenslinnhoff.github.io/OpenMATERIAL/asamopenmaterial/latest/specification/index.html

## Issue ticket number and link

Fixes #46, fixes #51, fixes #109 

## Checklist before requesting a review

- [x] I have performed a self-review of my code/documentation.
- [x] My changes generate no new warnings during the documentation generation.

### CODE REVIEW

**Review by AsamDiegoSanchez — APPROVED** [review]
Reviewed
Signed-off by: Diego Sánchez <diego.sanchez@asam.net>

**Comment by ClemensLinnhoff** [comment]
@LudwigFriedmann could you also review this, if the new structure would work for you? This also contains the decision to have a material texture assignment in the asset file and the material mapping in a separate mapping file.
The description of the general file structure however is not implemented here, yet.

**Comment by ClemensLinnhoff** [comment]
As soon as this is merged I will create an example to showcase both the mapping via texture and via mesh.

**Review by LudwigFriedmann — APPROVED** [review]
LGTM

**Pull request merged**
